### ISSUE TITLE
Error when changing the description of a column

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#32]
Hi. I have been testing 0.1.10 a bit and got some error whenever I try to update the description of columns:

```
[2021-06-18 09:10:55,507] ERROR in app: Exception on /api/v1/update_metadata [POST]
Traceback (most recent call last):
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata.py", line 55, in update_metadata
    return tangata_api.update_metadata(request.json)
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata_api.py", line 354, in update_metadata
    currentSchemaYMLModelColumn = list(filter(lambda d: d['name'] == jsonBody['column'], currentSchemaYMLModel['columns']))[0]
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata_api.py", line 354, in <lambda>
    currentSchemaYMLModelColumn = list(filter(lambda d: d['name'] == jsonBody['column'], currentSchemaYMLModel['columns']))[0]
TypeError: string indices must be integers
```

**Comment by ciejer** [comment]
Fixed - will be in 0.1.11 released shortly
