### ISSUE TITLE
Error in editing tags

### ISSUE THREAD

**Issue by ciejer** [ciejer/tangata_local#34]
Error when removing a tag:

[2021-06-19 22:58:07,787] ERROR in app: Exception on /api/v1/update_metadata [POST]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python36\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\lib\site-packages\tangata\tangata.py", line 58, in update_metadata
    updateResult = tangata_api.update_metadata(request.json, sendToast)
  File "c:\python36\lib\site-packages\tangata\tangata_api.py", line 311, in update_metadata
    newDBTProjectYML = merge(dbtProjectYML, jsonToInsert)
  File "c:\python36\lib\site-packages\tangata\tangata_api.py", line 271, in merge
    merge(a[key], b[key], path + [str(key)])
  File "c:\python36\lib\site-packages\tangata\tangata_api.py", line 271, in merge
    merge(a[key], b[key], path + [str(key)])
  File "c:\python36\lib\site-packages\tangata\tangata_api.py", line 271, in merge
    merge(a[key], b[key], path + [str(key)])
  [Previous line repeated 1 more time]
  File "c:\python36\lib\site-packages\tangata\tangata_api.py", line 275, in merge
    raise Exception('Conflict at %s' % '.'.join(path + [str(key)]))
Exception: Conflict at models.my_new_project.analytics.customer_film_categories.tags

**Comment by ciejer** [comment]
Resolved in 0.1.12
