### ISSUE TITLE
v0.1.16 - KeyError: 'promotion_tag'

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#45]
Hi.

Just got this issue when running 0.1.16

```
Job "tangata.<locals>.run_first_load (trigger: date[2021-06-27 21:29:07 AEST], next run at: 2021-06-27 21:29:07 AEST)" raised an exception
Traceback (most recent call last):
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata.py", line 108, in run_first_load
    tangata_api.reload_dbt(sendToast)
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata_api.py", line 446, in reload_dbt
    refreshMetadata(sendToast)
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata_api.py", line 66, in refreshMetadata
    assemblingFullCatalog = tangata_catalog_compile.compileCatalogNodes()
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata_catalog_compile.py", line 89, in compileCatalogNodes
    tempCatalogNodes[key] = populateFullCatalogNode(catalog['nodes'][key], "node", catalog, manifest)
  File "/home/xxx/envs/dbt19/lib/python3.8/site-packages/tangata/tangata_catalog_compile.py", line 31, in populateFullCatalogNode
    if len(tangataConfig["promotion_tag"]) > 0 and tangataConfig["promotion_tag"] in manifestNode['tags']:
KeyError: 'promotion_tag'
```

**Comment by ciejer** [comment]
Fixed in 0.1.18 - new config values were causing issues if they don't exist on version upgrade
